name: Build AuthenticationService

on:
  push:
    branches:
      - main
      - development
    paths:
      - "AuthenticationService/**"
      - "AuthenticationService.Test/**"
      - ".github/workflows/build-authentication-service.yml"
  pull_request:
    branches: 
      - main
      - development
    paths:
      - "AuthenticationService/**"
      - "AuthenticationService.Test/**"
      - ".github/workflows/build-authentication-service.yml"
env:
  PROJECT_PATH: 'AuthenticationService/AuthenticationService.csproj'
  TEST_PATH: 'AuthenticationService.Test/AuthenticationService.Test.csproj'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_AUTH_SERVICE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
      
    - name: 'Run tests'
      run: dotnet test ${{ env.TEST_PATH }}

    # https://github.com/highbyte/sonarscan-dotnet
    - name: SonarScanner for .NET 6
      uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
      with:
        args:
          -Dsonar.projectKey=authentication_service
          -Dsonar.organization=dmitri-lisokonov
          -Dsonar.projectBaseDir=./AuthenticationService
          -Dsonar.tests=AuthenticationService.Test



