name: Build MessageService

on:
  push:
    branches:
      - main
      - development
    paths:
      - "MessageService/**"
      - "MessageService.Test/**"
      - ".github/workflows/build-message-service.yml"
  pull_request:
    branches: 
      - main
      - development
    paths:
      - "MessageService/**"
      - "MessageService.Test/**"
      - ".github/workflows/build-message-service.yml"
env:
  PROJECT_PATH: 'MessageService/MessageService.csproj'
  TEST_PATH: 'MessageService.Test/MessageService.Test.csproj'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_MESSAGE_SERVICE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
      
    - name: 'Run tests'
      run: dotnet test ${{ env.TEST_PATH }}

    # https://github.com/highbyte/sonarscan-dotnet
    - name: SonarScanner for .NET 6
      uses: highbyte/sonarscan-dotnet@2.0
      with:
        sonarProjectKey: dmitri-lisokonov_twinstagram_message-service
        sonarProjectName:  dmitri-lisokonov_twinstagram_message-service
        sonarOrganization: dmitri-lisokonov
        dotnetBuildArguments: ./MessageService
        dotnetTestArguments: ./MessageService.Test



